version: '3.8'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1-python3.11
  env_file: 
    - .env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - _PIP_ADDITIONAL_REQUIREMENTS=pandas sqlalchemy psycopg2-binary beautifulsoup4 requests streamlit lxml minio python-dotenv
    - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src  
  depends_on:
    postgres:
      condition: service_healthy
    minio:
      condition: service_started

services:
  postgres:
    image: postgres:18
    env_file: 
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    env_file: 
      - .env
    ports:
      - "9000:9000" 
      - "9001:9001" 
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - _AIRFLOW_DB_UPGRADE=True
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  streamlit:
    image: python:3.11-slim
    working_dir: /app
    env_file: 
      - .env
    volumes:
      - .:/app
    command: >
      bash -c "pip install pandas sqlalchemy psycopg2-binary streamlit python-dotenv &&
               streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  minio_data: